# Generated by Django 3.1.7 on 2021-03-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_auto_20210305_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='isLoan',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Bank Account', 'Bank Account'), ('Loan', 'Loan')], default='Bank Account', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rank',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='Basic', max_length=200),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('text', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id_account_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.account')),
            ],
        ),
    ]
