# Generated by Django 3.1.7 on 2021-03-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
