# Generated by Django 3.2 on 2021-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_auto_20210513_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
