# Generated by Django 3.2 on 2021-05-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_customer_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_employee',
        ),
    ]
