# Generated by Django 3.2 on 2021-06-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_remove_customer_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalledger',
            name='comments',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
