# Generated by Django 3.2 on 2021-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0011_externalledger_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalledger',
            name='comments',
            field=models.CharField(max_length=100),
        ),
    ]
