# Generated by Django 3.2 on 2021-06-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0011_externalledger_comments 2'),
        ('bank_app', '0012_alter_externalledger_comments'),
        ('bank_app', '0012_alter_externalledger_comments 2'),
    ]

    operations = [
    ]
