# Generated by Django 3.2 on 2021-06-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0012_alter_externalledger_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalledger',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
