# Generated by Django 3.2 on 2021-06-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0013_alter_externalledger_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
