# Generated by Django 3.2 on 2021-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0013_merge_20210620_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalledger',
            name='comments',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='externalledger',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
