# Generated by Django 3.2 on 2021-06-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0014_auto_20210620_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='id_account_fk',
            new_name='account',
        ),
    ]
