# Generated by Django 3.2 on 2021-06-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0014_alter_ledger_transaction_id'),
        ('bank_app', '0015_rename_id_account_fk_ledger_account'),
    ]

    operations = [
    ]
